# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.5
        environment:
          PIPENV_VENV_IN_PROJECT: true
          DATABASE_URL: postgresql://hirokazu@localhost/testserver
      - image: circleci/postgres:10.3-alpine-postgis-ram
        environment:
          POSTGRES_USER: hirokazu
          POSTGRES_DB: testserver

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
                  # - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-
      
      - run:
          name: Installing Psycopg Outside Environment Just in Case
          command: |
            sudo apt-get install python3-psycopg2

      - run:
          name: Run Virtual Environment and Install Requirements
          command: |
            python3 -m venv venv && . venv/bin/activate && python3 -m pip install -r requirements.txt

          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}
      
      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: Run Them Tests
          command: |
            . venv/bin/activate && python3 manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
          
