# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 09:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20180508_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 8, 9, 4, 13, 934215, tzinfo=utc)),
        ),
    ]
