# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-08 05:57
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('affiliation', models.CharField(max_length=64)),
                ('floors_above', models.IntegerField(default=1)),
                ('floors_below', models.IntegerField(default=0)),
                ('construction_date', models.DateTimeField(default=None)),
                ('added_date', models.DateTimeField(auto_now=True)),
                ('general_info', models.CharField(default=None, max_length=512)),
                ('address', models.CharField(max_length=256)),
                ('latitude', models.FloatField(default=None)),
                ('longitude', models.FloatField(default=None)),
                ('structure_type', models.CharField(choices=[('Wood', 'Wood'), ('Concrete', 'Concrete'), ('Reinforced Concrete', 'Reinforced Concrete'), ('Reinforced Steel', 'Reinforced Steel'), ('Steel Reinforced Concrete', 'Steel Reinforced Concrete'), ('Steel', 'Steel'), ('Base Isolated', 'Base Isolated'), ('Other', 'Other')], default=None, max_length=20)),
                ('height', models.FloatField(default=None)),
                ('width_ns', models.FloatField(default=None)),
                ('width_ew', models.FloatField(default=None)),
                ('contex_info', models.CharField(default=None, max_length=512)),
                ('acc_top_floor', models.IntegerField()),
                ('acc_top_detail', models.CharField(max_length=512)),
                ('acc_bot_floor', models.IntegerField()),
                ('acc_bot_detail', models.CharField(max_length=512)),
                ('sampling_rate', models.FloatField()),
                ('conversion_factor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('event_time', models.DateTimeField(default=datetime.datetime(2018, 5, 8, 5, 57, 18, 948009, tzinfo=utc))),
                ('duration', models.TimeField()),
                ('intensity', models.FloatField()),
                ('acceleration', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Building')),
            ],
        ),
    ]
