# Generated by Django 2.0.5 on 2018-05-10 07:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20180508_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 10, 7, 12, 21, 759103, tzinfo=utc)),
        ),
    ]
