# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 06:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20180510_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 12, 6, 28, 0, 389566, tzinfo=utc)),
        ),
    ]
